FROM postgres:18.1-alpine@sha256:aa6eb304ddb6dd26df23d05db4e5cb05af8951cda3e0dc57731b771e0ef4ab29
COPY infrastructure/docker/postgres-init/01-keycloak-database.sh /docker-entrypoint-initdb.d/01-keycloak-database.sh

